services:
  backend:
    build: .
    container_name: clevercookin_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn Application.main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: bitnami/postgresql:latest
    container_name: clevercookin_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=clevercookin
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clevercookin"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-replica:
    image: bitnami/postgresql:latest
    container_name: clevercookin_db_replica
    ports:
      - "5433:5432"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=db
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    volumes:
      - postgres_replica_data:/bitnami/postgresql
    restart: always

volumes:
  postgres_data:
  postgres_replica_data: