services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clevercookin_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - clevercookin_network

  db:
    image: postgres:15
    container_name: clevercookin_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clevercookin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - clevercookin_network

volumes:
  postgres_data:

networks:
  clevercookin_network: