"""add search indexes

Revision ID: 31127b0037cc
Revises: 29f93f18121a
Create Date: 2026-02-26 15:52:34.278075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31127b0037cc'
down_revision: Union[str, Sequence[str], None] = '29f93f18121a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_recipeingredient_ingredient_id', 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index('idx_recipeingredient_recipe_id', 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_index('idx_useringredient_ingredient_id', 'user_ingredients', ['ingredient_id'], unique=False)
    op.create_index('idx_useringredient_user_id', 'user_ingredients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_useringredient_user_id', table_name='user_ingredients')
    op.drop_index('idx_useringredient_ingredient_id', table_name='user_ingredients')
    op.drop_index('idx_recipeingredient_recipe_id', table_name='recipe_ingredients')
    op.drop_index('idx_recipeingredient_ingredient_id', table_name='recipe_ingredients')
    # ### end Alembic commands ###
